#! /bin/bash
set -e

# https://www.golinuxcloud.com/openssl-create-certificate-chain-linux/

# Create CA key + cert
openssl req \
    -x509 \
    -nodes \
    -sha256 \
    -days 365 \
    -newkey rsa:4096 \
    -keyout ca.key \
    -out ca.cert.pem \
    -subj "/C=NL/ST=./L=./O=Brewblox/OU=./CN=brewblox-ca"

# Generate server key + CSR (cert sign request)
openssl req \
    -nodes \
    -newkey rsa:4096 \
    -keyout server.key \
    -out server.csr \
    -subj "/C=NL/ST=./L=./O=Brewblox/OU=./CN=brewblox-server"

# Sign CSR
openssl x509 \
    -req \
    -days 365 \
    -in server.csr \
    -CA ca.cert.pem \
    -CAkey ca.key \
    -CAcreateserial \
    -out server.crt
