#! /bin/bash
set -e

openssl req \
    -x509 \
    -nodes \
    -days 365 \
    -newkey rsa:2048 \
    -sha256 \
    -config /usr/local/etc/brewblox-certs.cnf \
    -extensions req_ext \
    -keyout brewblox.key \
    -out brewblox.crt
